---
title: "Dynamic Predictions"
author: "Dimitris Rizopoulos"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Dynamic Predictions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library("JMbayes2")
```

# Dynamic Predictions
## PBC Dataset
```{r}
pbc2.id$status2 <- as.numeric(pbc2.id$status != 'alive')
CoxFit <- coxph(Surv(years, status2) ~ sex, data = pbc2.id)
fm1 <- lme(log(serBilir) ~ ns(year, 3) * sex, data = pbc2, 
           random = ~ ns(year, 3) | id, control = lmeControl(opt = 'optim'))
fm2 <- lme(prothrombin ~ ns(year, 2) * sex, data = pbc2, 
           random = ~ ns(year, 2) | id, control = lmeControl(opt = 'optim'))
fm3 <- mixed_model(ascites ~ year * sex, data = pbc2,
                   random = ~ year | id, family = binomial())

jointFit <- jm(CoxFit, list(fm1, fm2, fm3), time_var = "year", 
               n_iter = 13000L, n_burnin = 3000L)
```

```{r}
t0 <- 3
ND <- pbc2[pbc2$id %in% c(2, 25), ]
ND <- ND[ND$year < t0, ]
ND$status2 <- 0
ND$years <- t0
```

```{r}
predLong1 <- predict(jointFit, newdata = ND, return_newdata = TRUE)
```

```{r}
library("lattice")
xyplot(pred_serBilir + low_serBilir + upp_serBilir ~ year | id, data = predLong1, 
       type = "l", lwd = 2, col = c(2, 1, 1), lty = c(1, 2, 2),
       abline = list(v = t0, lty = 3), 
       xlab = "Follow-up Time (years)", 
       ylab = "Log(serum Bilirubin (mg/dL))")

xyplot(pred_ascites + low_ascites + upp_ascites ~ year | id,  data = predLong1, 
       type = "l", lwd = 2, col = c(2, 1, 1), lty = c(1, 2, 2),
       abline = list(v = t0, lty = 3),
       xlab = "Follow-up Time (years)", 
       ylab = "Probability of Ascites")
```

```{r}
predLong2 <- predict(jointFit, newdata = ND,
                     times = seq(t0, 10, length.out = 51),
                     return_newdata = TRUE)
plot_data <- rbind(predLong2[[1]], predLong2[[2]])

xyplot(pred_serBilir + low_serBilir + upp_serBilir ~ year | id, 
       data = plot_data, type = "l", lwd = 2, col = c(2, 1, 1), lty = c(1, 2, 2),
       abline = list(v = t0, lty = 3), xlab = "Follow-up Time (years)", 
       ylab = "Log(serum Bilirubin (mg/dL))")

xyplot(pred_prothrombin + low_prothrombin + upp_prothrombin ~ year | id, 
       data = plot_data, type = "l", lwd = 2, col = c(2, 1, 1), lty = c(1, 2, 2),
       abline = list(v = t0, lty = 3), xlab = "Follow-up Time (years)", 
       ylab = "Prothrombin Time (sec)")

```

```{r}
predSurv <- predict(jointFit, newdata = ND, process = "event",
                    times = seq(t0, 10, length.out = 51),
                    return_newdata = TRUE)

xyplot(pred_CIF + low_CIF + upp_CIF ~ year | id, data = predSurv,
       type = "l", lwd = 2, col = c(2, 1, 1), lty = c(1, 2, 2),
       abline = list(v = t0, lty = 3), grid = TRUE,
       xlab = "Follow-up Time (years)", 
       ylab = "Cumulative Incidence")
```
