// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mcmc_cpp
List mcmc_cpp(List model_data, List model_info, List initial_values, List priors, List control, List vcov_prop);
RcppExport SEXP _JMbayes2_mcmc_cpp(SEXP model_dataSEXP, SEXP model_infoSEXP, SEXP initial_valuesSEXP, SEXP priorsSEXP, SEXP controlSEXP, SEXP vcov_propSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model_data(model_dataSEXP);
    Rcpp::traits::input_parameter< List >::type model_info(model_infoSEXP);
    Rcpp::traits::input_parameter< List >::type initial_values(initial_valuesSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< List >::type vcov_prop(vcov_propSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_cpp(model_data, model_info, initial_values, priors, control, vcov_prop));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_JMbayes2_mcmc_cpp", (DL_FUNC) &_JMbayes2_mcmc_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_JMbayes2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
