# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcmc_cpp <- function(model_data, model_info, initial_values, priors, control, vcov_prop) {
    .Call(`_JMbayes2_mcmc_cpp`, model_data, model_info, initial_values, priors, control, vcov_prop)
}

logLik_jm <- function(thetas, model_data, model_info, control) {
    .Call(`_JMbayes2_logLik_jm`, thetas, model_data, model_info, control)
}

